import { IRestCountriesStrings } from './RestCountriesStrings';

export const strings: IRestCountriesStrings = {
    header_HideInfo: 'Amaga els Crèdits',
    header_ShowInfo: 'Mostra els Crèdits',
    label_LoadFromRestcountries: 'Descarregueu les Banderes de restcountries.eu',
    click_ToViewTimeZones: "Deixa quiet el ratolí para veure els Fusos Horaris",
    click_ToSeeFlag: "Fes clic per veure la Bandera del Pais",
    click_ToSeeFlagOf: "Fes clic per veure la Bandera de",
    label_FlagOf: "Bandera de",
    click_ToGoWikipediaInSpanish: "Fes clic per anar a la 'Wikipedia' en Espanyol",
    click_ToGoWikipediaInEnglish: "Fes clic per anar a la 'Wikipedia' en Anglès",
    click_ToSeeCapitalInGoogleMaps: "Fes clic per veure la Capital del Pais a 'Google Maps'",
    click_ToSeeCountryInGoogleMaps: "Fes clic per veure el Pais a 'Google Maps'",
    click_ToSeeContinentInGoogleMaps: "Fes clic per veure el Continent a 'Google Maps'",
    click_ToSeeregionInGoogleMaps: "Fes clic per veure la Regiò a 'Google Maps'",
    config_SelectColors: 'Seleccionar Colors',
    color_Blue: 'Blau',
    color_Green: 'Vert',
    color_Red: 'Roig',
    color_Grays: 'Grisos',
    color_Yellow: 'Groc',
    color_Magenta: "Magenta",
    color_Cyan: "Cyan",
    config_SelectLanguage: "Seleccionar Idioma",
    header_ShowConfig: 'Mostra la Configuració',
    header_HideConfig: 'Amaga la Configuració',
    config_CompactMode: 'Mostra la llista en mode "Compacte"',
    agradecimiento: 'agraiments a',
    model_Loading: 'Carregant els Països ...',
    title_App: 'Països i Banderes del Món',
    label_Paises: 'Països',
    label_Pais: 'Pais',
    label_Idiomas: 'Llengües parlades a',
    field_NumHusos: 'Fusos Horaris',
    field_Idiomas: 'Idiomes',
    field_Siglas: 'Sigles',
    field_Region: 'Regiò',
    field_Continente: 'Continent',
    field_Capital: 'Capital',
    field_SpanishName: 'Nom Espanyol',
    field_EnglishName: 'Nom Anglès',
    field_NativeName: 'Nom Natiu',
    field_Flag: 'Bandera',
}

