import { IRestCountriesStrings } from './RestCountriesStrings';

export const strings: IRestCountriesStrings = {
    click_ToViewTimeZones: "Hold your mouse still to see Time zones",
    click_ToSeeFlag: "Click to see the Flag",
    click_ToGoWikipediaInSpanish: "Click to go to the 'Wikipedia' in Spanish",
    click_ToGoWikipediaInEnglish: "Click to go to the 'Wikipedia' in English",
    click_ToSeeCapitalInGoogleMaps: "Click to see the Capital of the Country in 'Google Maps'",
    click_ToSeeCountryInGoogleMaps: "Click to see the Country in 'Google Maps'",
    click_ToSeeContinentInGoogleMaps: "Click to see the Continent in 'Google Maps'",
    click_ToSeeregionInGoogleMaps: "Click to see the Region in 'Google Maps'",
    config_SelectColors: 'Select Colors',
    color_Blue: 'Blue',
    color_Green: 'Green',
    color_Red: 'Red',
    color_Grays: 'Gray',
    color_Yellow: 'Yellow',
    color_Magenta: "Magenta",
    color_Cyan: "Cyan",
    config_SelectLanguage: "Select Language",
    header_ShowConfig: 'Show Settings',
    header_HideConfig: 'Hide Settings',
    config_CompactMode: 'Displays the list in "Compact" mode',
    agradecimiento: 'thanks to the Rest Service ',
    model_Loading: 'Loading ...',
    title_App: 'Countries and Flags of the World',
    label_Paises: 'Countries',
    label_Pais: 'Country',
    field_NumHusos: 'Time Zones',
    field_Idiomas: 'Languages',
    field_Siglas: 'Acronym',
    field_Region: 'Region',
    field_Continente: 'Continent',
    field_Capital: 'Capital',
    field_SpanishName: 'Spanish name',
    field_EnglishName: 'English name',
    field_NativeName: 'Native name',
    field_Flag: 'Flag',
}

