import { IRestCountriesStrings } from './RestCountriesStrings';

export const strings: IRestCountriesStrings = {
    header_HideInfo: 'Cerrar los Créditos',
    header_ShowInfo: 'Mostrar los Créditos',
    label_LoadFromRestcountries: 'Descargar las Banderas de restcountries.eu',
    click_ToViewTimeZones: "Mantén quieto el ratón para ver los Husos Horarios",
    click_ToSeeFlag: "Clica para ver la Bandera",
    click_ToGoWikipediaInSpanish: "Clica para ir a la 'Wikipedia' en Español",
    click_ToGoWikipediaInEnglish: "Clica para ir a la 'Wikipedia' en Inglés",
    click_ToSeeCapitalInGoogleMaps: "Clica para ver la Capital del Pais en 'Google Maps'",
    click_ToSeeCountryInGoogleMaps: "Clica para ver el Pais en 'Google Maps'",
    click_ToSeeContinentInGoogleMaps: "Clica para ver el Continente en 'Google Maps'",
    click_ToSeeregionInGoogleMaps: "Clica para ver la Region en 'Google Maps'",
    config_SelectColors: 'Selecciona Colores',
    color_Blue: 'Azul',
    color_Green: 'Verde',
    color_Red: 'Rojo',
    color_Grays: 'Grises',
    color_Yellow: 'Amarillo',
    color_Magenta: "Magenta",
    color_Cyan: "Cyan",
    config_SelectLanguage: "Seleccionar Idioma",
    header_ShowConfig: 'Mostrar la Configuración',
    header_HideConfig: 'Cerrar la Configuración',
    config_CompactMode: 'Mostrar la lista en modo "Compacto"',
    agradecimiento: 'agradecimientos a',
    model_Loading: 'Cargando ...',
    title_App: 'Paises y Banderas del Mundo',
    label_Paises: 'Paises',
    label_Pais: 'Pais',
    field_NumHusos: 'Husos horarios',
    field_Idiomas: 'Idiomas',
    field_Siglas: 'Siglas',
    field_Region: 'Región',
    field_Continente: 'Continente',
    field_Capital: 'Capital',
    field_SpanishName: 'Nombre Español',
    field_EnglishName: 'Nombre Inglés',
    field_NativeName: 'Nombre Nativo',
    field_Flag: 'Bandera',
}
