import { IRestCountriesStrings } from './RestCountriesStrings';

export const strings: IRestCountriesStrings = {
    header_HideInfo: 'Masquer les Crédits',
    header_ShowInfo: 'Afficher les Crédits',
    label_LoadFromRestcountries: 'Téléchargez les Drapeaux sur restcountries.eu',
    click_ToViewTimeZones: "Maintenez votre souris immobile pour voir les Fuseaux horaires",
    click_ToSeeFlag: "Cliquez pour voir le Drapeau",
    click_ToGoWikipediaInSpanish: "Cliquez pour aller à la 'Wikipedia' en Espagnol",
    click_ToGoWikipediaInEnglish: "Cliquez pour aller à la 'Wikipedia' en Anglais",
    click_ToSeeCapitalInGoogleMaps: "Cliquez pour voir la Capitale du Pays dans 'Google Maps'",
    click_ToSeeCountryInGoogleMaps: "Cliquez pour voir le Pays dans 'Google Maps'",
    click_ToSeeContinentInGoogleMaps: "Cliquez pour voir le Continent dans 'Google Maps'",
    click_ToSeeregionInGoogleMaps: "Cliquez pour voir la Région dans 'Google Maps'",
    config_SelectColors: 'Sélectionner les Couleurs',
    color_Blue: 'Bleu',
    color_Green: 'Verte',
    color_Red: 'Rouge',
    color_Grays: 'Gris',
    color_Yellow: 'Jaune',
    color_Magenta: "Magenta",
    color_Cyan: "Cyan",
    config_SelectLanguage: "Sélectionner la Langue",
    header_ShowConfig: 'Afficher les Paramètres',
    header_HideConfig: 'Masquer les Paramètres',
    config_CompactMode: 'Affiche la liste en mode "Compact"',
    agradecimiento: 'grâce au',
    model_Loading: 'Attendez quelques secondes',
    title_App: 'Pays et Drapeaux du Monde',
    label_Paises: 'Pays',
    label_Pais: 'Pays',
    field_NumHusos: 'Fuseaux horaires',
    field_Idiomas: 'Langues',
    field_Siglas: 'Acronymes',
    field_Region: 'Région',
    field_Continente: 'Continent',
    field_Capital: 'Capitale',
    field_SpanishName: 'Nom Espagnol',
    field_EnglishName: 'Nom Anglais',
    field_NativeName: 'Nom natif',
    field_Flag: 'Drapeau',
}
